#ifndef CONSTS_H
#define CONSTS_H

#include <SDL.h>
#include <SDL_main.h>


// proporcje widoku itd
#define SCREEN_WIDTH	640
#define SCREEN_HEIGHT	480
#define LEVEL_WIDTH 2000

#define BACKGROUND_HEIGHT (SCREEN_HEIGHT / 5) * 2// 2/5 ekranu
#define FLOOR_HEIGHT (SCREEN_HEIGHT - BACKGROUND_HEIGHT) // 3/5ekranu

#define BACKGROUND_WIDTH SCREEN_WIDTH
#define FLOOR_WIDTH SCREEN_WIDTH

#define FLOOR_ZERO_Y  (BACKGROUND_HEIGHT)
#define FLOOR_ZERO_X 0

#define UP -1
#define DOWN 1
#define LEFT -1
#define RIGHT 1


// combo define'y
#define MAX_COMBOS_TRACKED 100
#define COMBO_TIMEOUT_MS 200.0f

#define FIRST_COMBO_a {SDL_SCANCODE_D, SDL_SCANCODE_D}
#define FIRST_COMBO_b {SDL_SCANCODE_RIGHT, SDL_SCANCODE_RIGHT}
#define SECOND_COMBO_a {SDL_SCANCODE_Q, SDL_SCANCODE_Q, SDL_SCANCODE_Q}
#define THIRD_COMBO_a {SDL_SCANCODE_E, SDL_SCANCODE_Q, SDL_SCANCODE_E}
#define MAX_COMBO_STEPS 3
//

// stale atakowe
#define LIGHT_ATTACK_WIDTH 60
#define LIGHT_ATTACK_HEIGHT 40
#define HEAVY_ATTACK_WIDTH 80
#define HEAVY_ATTACK_HEIGHT 50
//


// stale dla wrogow
#define MAX_ENEMIES 40

#define WALKER_MAX_HP 100
#define WALKER_WIDTH 50
#define WALKER_HEIGHT 50
#define WALKER_DAMAGE 20
#define WALKER_ATTACK_RANGE 100
#define WALKER_ATTACK_COUNTDOWN 1
#define WALKER_SPEED 50

#define CHARGER_MAX_HP 200
#define CHARGER_WIDTH 50
#define CHARGER_HEIGHT 50
#define CHARGER_DAMAGE 35
#define CHARGER_ATTACK_RANGE 30
#define CHARGER_ATTACK_COUNTDOWN 1
#define CHARGER_SPEED 40
//



#endif